# Generated by Django 5.2 on 2025-05-29 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicFactorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.economicfactor')),
            ],
        ),
        migrations.CreateModel(
            name='HPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.economicfactor')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.state')),
            ],
        ),
        migrations.CreateModel(
            name='HousingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('housing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.housingtype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.state')),
            ],
        ),
    ]
