# Generated by Django 5.2 on 2025-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingprice',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
