# Generated by Django 5.2 on 2025-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_housingprice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicfactorvalue',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
