# Generated by Django 5.2 on 2025-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_economicfactorvalue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpi',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
